basic.forever(function () {
    if (input.temperature() > 22) {
        basic.showIcon(IconNames.Sad)
        basic.pause(100)
        basic.showIcon(IconNames.Butterfly)
    } else {
        basic.showIcon(IconNames.Sword)
        basic.pause(1000)
        basic.showIcon(IconNames.Ghost)
        basic.pause(1000)
        music.ringTone(131)
        basic.pause(500)
        music.ringTone(131)
        basic.pause(500)
        music.ringTone(165)
        basic.pause(500)
        music.ringTone(196)
        basic.pause(500)
        music.ringTone(196)
        basic.pause(500)
        music.ringTone(220)
        basic.pause(1000)
        music.ringTone(131)
        basic.pause(500)
        music.ringTone(131)
        basic.pause(500)
        music.ringTone(165)
    }
})
